### ISSUE TITLE
Need to add the "overtemp" alert to block payload

### ISSUE THREAD

**Issue by mna2016** [ibm-watson-iot/blockchain-samples#33]
The use case I am working on, has a transaction history on the right hand side of the screen. The transaction history shows the blockchain blocks in the order of their creation timestamp. The blocks will show "create" or "update" transaction on an asset.

we have already updated the code to have an overtemp alert in place. The overtemp alert is setting the compliant flag to TRUE or FALSE based on the temperature read. This part is ok.

What we now need is, when "OVERTEMP" alert is detected, the OVERTEMP string should be displayed in the payload of the transaction which updated the blockchain(I have tried updating chaincode the dirty way in order to accomplish this but nothing has worked so far).

What is the simplest and correct way of doing it ?

Appreciate the help of readers in this regard. Thanks.

**Comment by kletkeman** [comment]
You need to decide how you are going to get that info. The block contains a transaction and any emitted events, but the alert status (active, raised and cleared) is calculated as part of state. Luckily, if you are basing your code off of the IOT Contract Platform, the emitted chaincode event payloads contain the alert status for successful transactions. Thus, you get a wee taste of world state when you either listen for the event, or process every block and tie the txn id back to the asset (thus relating the alert status to the asset from which it came).

Note that v0.6 has some strange behaviors around block formats. Failed transactions do not appear in the transaction array but their events do appear in the secondary events array. I wrote some code to handle that in the monitoring UI application in this repository. You basically process both arrays using a map by transaction ID and you end up with all transactions that were successful or emitted an event or both.

If your contract is not based on the iot contract platform, consider adapting your code to the container sample under "platform" ...

**Comment by mna2016** [comment]
Hi kletkeman,

Many Thanks for the quick reply!

Our use case is indeed based on the iot contract platform.

As you pointed in your reply i.e. "..the emitted chaincode event payloads contain the alert status for successful transactions..." - 

1) How do I read the emitted event payload?  Is there a sample code\github link which does this that I can refer to.

2) Please note that I am able to see the overtemp alert when I do a "query" on assets. But what instead we would like is to show the audience that the block's payload recorded "Overtemp" alert in the block itself(by showing them a list of block payloads).


Appreciate your suggestions\guidance in this regard.

**Comment by kletkeman** [comment]
Here is a golang program that can listen for events in v0.6 ... have not tried on v1. It could fire those events at your app for now. Or you could use the node sdk for v1. 
https://github.com/ibm-watson-iot/blockchain-samples/tree/master/applications/event_listener

Here is the monitoring ui app, which has code in it to interpret the contents of blocks. Note that it actually keeps track of the last block it has seen and polls every 2s for the chain height, fetching all new blocks since the last poll. This is a very easy mechanism, but does not exist in v1. If you are on v0.6, then it can tie you over for now.
https://github.com/ibm-watson-iot/blockchain-samples/tree/master/applications/monitoring_ui

**Comment by mna2016** [comment]
Many thanks for the quick response!
My use case now is able to interpret the alert inside of block's payload.

Thanks again!

**Comment by kletkeman** [comment]
You are very welcome. I am closing the issue as solved, but feel free to open another issue if you run into problems.
