### ISSUE TITLE
stateHash is not matching previousBlockHash

### ISSUE THREAD

**Issue by mna2016** [ibm-watson-iot/blockchain-samples#36]
As per the blockchain theory that I have understood so far, The blocks are connected via "Hash" keys. i.e. Two fields "stateHash" and "previousBlockHash" are present on each block. As per my understanding previousBlockHash of the present block should be equal to the stateHash of the previous block.

I have deployed this chaincode via IBM bluemix blockchain service. The stateHash and previousBlockHash are not equal for most of the blocks. 

Is this a problem? Please clarify.

**Comment by kletkeman** [comment]
I've not seen the issue that you are seeing. Make sure that you decode any encoded payload values using an online base64 decoder. Once you have everything in plain text, you should see that the has of block X is the same as the previousBlockHash of block X+1.

**Comment by mna2016** [comment]
Yes this my incorrect understanding of the blockchain hash keys. Now resolved. Thanks for the clarification.

**Comment by mna2016** [comment]
Should now be closed.
