### ISSUE TITLE
Explanation on the simple contract example is needed.

### ISSUE THREAD

**Issue by jackzhp** [ibm-watson-iot/blockchain-samples#41]
I was hoping in its first paragraph, the author can tell what is contract before going into technical details. Anyone can help?

As for a contract, I would expect there are at least two parties involved, and then rights and responsibilities are defined for each party. Once the contract is signed, both parties should honour the contract, ie. deliver as contracted, once all responsibilities are delivered, the contract is cleared. 

Isn't it? But in its explanation, I did not see any of what I am looking for. Why is so? thanks.

**Comment by HNorlen** [comment]
Here's the official description used by IBM:
> # smart contract
>
> A set of business terms that are embedded into a blockchain and executed with transactions. A smart contract can also include a digital representation of a set of business rules and defines conditions under which transfers occur. A smart contract is implemented using chaincode.

For additional official IBM terms, select Blockchain in the glossary export page, then select your preferred format and download the glossary:
http://tlwi.w3-969.ibm.com/standards/terminology/cgi-bin/GDWI.exe

**Comment by kletkeman** [comment]
@jackzhp My apologies for not seeing this question come up last month. Hassi's answer is right on of course, in that smart contracts are contracts mainly in the sense that they encapsulate business rules for transactions that manipulate the blockchain's world state.

You appear to be thinking in terms of contracts between two people and, while this is one sort of smart contract that can be written, it is but one small use case among many thousand possibilities. Smart contracts are used these days for banking (which at times comes very close to the use case you mentioned), shipping, track and trace, provenance, and so on. The list is nearly endless.

I like to think of smart contracts as similar in concept to servelets on a web server. They receive requests, validate them, and then change the state of the database. There is nothing more complex going on that that at the highest level. However, blockchains have much different performance and security characteristics that makes them more suitable for some use cases and less suitable for others.
